"""initial migration

Revision ID: 0385ed628827
Revises: 6dfaf06087da
Create Date: 2024-07-11 10:58:05.288852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0385ed628827'
down_revision: Union[str, None] = '6dfaf06087da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('order_rw_transport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_otpr_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('station_nazn_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'stations', ['station_nazn_id'], ['id'])
        batch_op.create_foreign_key(None, 'stations', ['station_otpr_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw_transport', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('station_nazn_id')
        batch_op.drop_column('station_otpr_id')

    with op.batch_alter_table('order_rw', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
