"""initial migration

Revision ID: 1514183349df
Revises: b65408f7a541
Create Date: 2024-07-09 13:54:38.212640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1514183349df'
down_revision: Union[str, None] = 'b65408f7a541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('contract_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('service_type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'service_types', ['service_type_id'], ['id'])
        batch_op.create_foreign_key(None, 'contracts', ['contract_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['manager_id'], ['id'])
        batch_op.create_foreign_key(None, 'contractors', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('service_type_id')
        batch_op.drop_column('contract_id')
        batch_op.drop_column('client_id')
        batch_op.drop_column('manager_id')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
