"""initial migration

Revision ID: 23aa25abc803
Revises: 9f9966efd83f
Create Date: 2024-07-11 10:32:04.597313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23aa25abc803'
down_revision: Union[str, None] = '9f9966efd83f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['rw_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subcodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subcodes_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subcodes_id'))

    op.drop_table('subcodes')
    # ### end Alembic commands ###
