"""Initial migration

Revision ID: 4eda31091f62
Revises: 
Create Date: 2024-06-26 21:01:30.626841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eda31091f62'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('guid', sa.String(length=100), nullable=True),
    sa.Column('bik', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('banks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banks_id'), ['id'], unique=False)

    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('guid', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_countries_id'), ['id'], unique=False)

    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('guid', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('copybook_parameters_ru', sa.String(length=200), nullable=True),
    sa.Column('copybook_parameters_en', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_currencies_id'), ['id'], unique=False)

    op.create_table('etsng',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('etsng', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etsng_id'), ['id'], unique=False)

    op.create_table('gng',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('code_etsng', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('code_etsng')
    )
    with op.batch_alter_table('gng', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gng_id'), ['id'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_id'), ['id'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)

    op.create_table('service_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_types_id'), ['id'], unique=False)

    op.create_table('territories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('territories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_territories_id'), ['id'], unique=False)

    op.create_table('vat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('guid', sa.String(length=100), nullable=True),
    sa.Column('rate', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vat_id'), ['id'], unique=False)

    op.create_table('wagon_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('official_name', sa.String(length=300), nullable=True),
    sa.Column('key_names', sa.String(length=500), nullable=True),
    sa.Column('platform', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('wagon_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wagon_types_id'), ['id'], unique=False)

    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('wagon_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wagon_type_id'], ['wagon_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_containers_id'), ['id'], unique=False)

    op.create_table('contractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('guid', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('bin', sa.String(length=15), nullable=False),
    sa.Column('kbe', sa.String(length=10), nullable=True),
    sa.Column('enterpreneur', sa.Boolean(), nullable=True),
    sa.Column('legal_address', sa.String(length=300), nullable=True),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('document', sa.String(length=300), nullable=True),
    sa.Column('owner_type', sa.Enum('Individual', 'Entity', name='ownertype'), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contractors_id'), ['id'], unique=False)

    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('vat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vat_id'], ['vat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_id'), ['id'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('guid', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('bin', sa.String(length=15), nullable=False),
    sa.Column('kbe', sa.String(length=10), nullable=True),
    sa.Column('enterpreneur', sa.Boolean(), nullable=True),
    sa.Column('legal_address', sa.String(length=300), nullable=True),
    sa.Column('owner_type', sa.Enum('Individual', 'Entity', name='ownertype'), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('territory_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(length=100), nullable=True),
    sa.Column('longitude', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stations_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('wagons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('wagon_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wagon_type_id'], ['wagon_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wagons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wagons_id'), ['id'], unique=False)

    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('guid', sa.String(length=100), nullable=True),
    sa.Column('number', sa.String(length=150), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['contractors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_accounts_id'), ['id'], unique=False)

    op.create_table('bank_accounts_org',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('guid', sa.String(length=100), nullable=True),
    sa.Column('number', sa.String(length=150), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_accounts_org', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_accounts_org_id'), ['id'], unique=False)

    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('guid', sa.String(length=100), nullable=True),
    sa.Column('number', sa.String(length=150), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_id'), ['id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('session_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('session_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('traffic', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_id'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_id'))

    op.drop_table('contracts')
    with op.batch_alter_table('bank_accounts_org', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_accounts_org_id'))

    op.drop_table('bank_accounts_org')
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_accounts_id'))

    op.drop_table('bank_accounts')
    with op.batch_alter_table('wagons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wagons_id'))

    op.drop_table('wagons')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stations_id'))

    op.drop_table('stations')
    op.drop_table('role_permissions')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_id'))

    op.drop_table('organizations')
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_id'))

    op.drop_table('operations')
    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contractors_id'))

    op.drop_table('contractors')
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_containers_id'))

    op.drop_table('containers')
    with op.batch_alter_table('wagon_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wagon_types_id'))

    op.drop_table('wagon_types')
    with op.batch_alter_table('vat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vat_id'))

    op.drop_table('vat')
    with op.batch_alter_table('territories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_territories_id'))

    op.drop_table('territories')
    with op.batch_alter_table('service_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_types_id'))

    op.drop_table('service_types')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_id'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_id'))

    op.drop_table('permissions')
    with op.batch_alter_table('gng', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gng_id'))

    op.drop_table('gng')
    with op.batch_alter_table('etsng', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etsng_id'))

    op.drop_table('etsng')
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_currencies_id'))

    op.drop_table('currencies')
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_countries_id'))

    op.drop_table('countries')
    with op.batch_alter_table('banks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banks_id'))

    op.drop_table('banks')
    # ### end Alembic commands ###
