"""initial migration

Revision ID: 58bfdcf9c338
Revises: 814f01a7c161
Create Date: 2024-07-11 11:16:58.102474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58bfdcf9c338'
down_revision: Union[str, None] = '814f01a7c161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw_transport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcode1_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subcode2_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subcode3_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subcode4_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subcode5_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('etsng_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gng_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'subcodes', ['subcode1_id'], ['id'])
        batch_op.create_foreign_key(None, 'subcodes', ['subcode3_id'], ['id'])
        batch_op.create_foreign_key(None, 'etsng', ['etsng_id'], ['id'])
        batch_op.create_foreign_key(None, 'gng', ['gng_id'], ['id'])
        batch_op.create_foreign_key(None, 'subcodes', ['subcode4_id'], ['id'])
        batch_op.create_foreign_key(None, 'subcodes', ['subcode5_id'], ['id'])
        batch_op.create_foreign_key(None, 'subcodes', ['subcode2_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw_transport', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gng_id')
        batch_op.drop_column('etsng_id')
        batch_op.drop_column('subcode5_id')
        batch_op.drop_column('subcode4_id')
        batch_op.drop_column('subcode3_id')
        batch_op.drop_column('subcode2_id')
        batch_op.drop_column('subcode1_id')

    # ### end Alembic commands ###
