"""initial migration

Revision ID: 5f0e67f724ed
Revises: 9bafb782cc4c
Create Date: 2024-07-11 13:24:06.166314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f0e67f724ed'
down_revision: Union[str, None] = '9bafb782cc4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw_transport', schema=None) as batch_op:
        batch_op.alter_column('wagon_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw_transport', schema=None) as batch_op:
        batch_op.alter_column('wagon_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
