"""initial migration

Revision ID: 6bc5c6f4a352
Revises: 6e317d3240a7
Create Date: 2024-07-09 17:09:19.338467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc5c6f4a352'
down_revision: Union[str, None] = '6e317d3240a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw_route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gng_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'gng', ['gng_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw_route', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gng_id')

    # ### end Alembic commands ###
