"""initial migration

Revision ID: 6e317d3240a7
Revises: eb16a30b32e4
Create Date: 2024-07-09 17:07:50.215425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e317d3240a7'
down_revision: Union[str, None] = 'eb16a30b32e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw_route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etsng_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'etsng', ['etsng_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw_route', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('etsng_id')

    # ### end Alembic commands ###
