"""initial migration

Revision ID: 7bdb18ba5b00
Revises: 0385ed628827
Create Date: 2024-07-11 11:05:13.478174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bdb18ba5b00'
down_revision: Union[str, None] = '0385ed628827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw_transport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wagon_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wagon_cn_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'wagons', ['wagon_cn_id'], ['id'])
        batch_op.create_foreign_key(None, 'wagons', ['wagon_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw_transport', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('wagon_cn_id')
        batch_op.drop_column('wagon_id')

    # ### end Alembic commands ###
