"""initial migration

Revision ID: 9169da0f8874
Revises: 23aa25abc803
Create Date: 2024-07-11 10:47:39.489078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9169da0f8874'
down_revision: Union[str, None] = '23aa25abc803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_rw_transport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('date_otpr', sa.Date(), nullable=True),
    sa.Column('date_otpr_sng', sa.Date(), nullable=True),
    sa.Column('date_transshipment', sa.Date(), nullable=True),
    sa.Column('date_arrive', sa.Date(), nullable=True),
    sa.Column('date_arrive_border', sa.Date(), nullable=True),
    sa.Column('profit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('rate', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('otpr_number', sa.String(length=100), nullable=True),
    sa.Column('sum', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('orderrw_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orderrw_id'], ['order_rw.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_rw_transport', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_rw_transport_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw_transport', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_rw_transport_id'))

    op.drop_table('order_rw_transport')
    # ### end Alembic commands ###
