"""initial migration

Revision ID: 9bafb782cc4c
Revises: 58bfdcf9c338
Create Date: 2024-07-11 12:13:10.425237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bafb782cc4c'
down_revision: Union[str, None] = '58bfdcf9c338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw_transport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('td', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('wagon_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vat_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'vat', ['vat_id'], ['id'])
        batch_op.create_foreign_key(None, 'wagon_types', ['wagon_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw_transport', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vat_id')
        batch_op.drop_column('wagon_type_id')
        batch_op.drop_column('td')

    # ### end Alembic commands ###
