"""initial migration

Revision ID: 9f9966efd83f
Revises: e46d3907734e
Create Date: 2024-07-11 10:15:54.553342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f9966efd83f'
down_revision: Union[str, None] = 'e46d3907734e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rw_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('territory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rw_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rw_codes_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rw_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rw_codes_id'))

    op.drop_table('rw_codes')
    # ### end Alembic commands ###
