"""initial migration

Revision ID: b65408f7a541
Revises: 10ca9ac31587
Create Date: 2024-07-09 13:13:24.301961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b65408f7a541'
down_revision: Union[str, None] = '10ca9ac31587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw', schema=None) as batch_op:
        batch_op.drop_constraint('order_rw_manager_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('order_rw_author_id_fkey', type_='foreignkey')
        batch_op.drop_column('manager_id')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('order_rw_author_id_fkey', 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key('order_rw_manager_id_fkey', 'users', ['manager_id'], ['id'])

    # ### end Alembic commands ###
