"""initial migration

Revision ID: dc296598ea64
Revises: 5f0e67f724ed
Create Date: 2024-07-11 14:06:43.142594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc296598ea64'
down_revision: Union[str, None] = '5f0e67f724ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_rw_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('sum_plan', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('sum_fact', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('card_number', sa.String(length=100), nullable=True),
    sa.Column('scroll', sa.String(length=100), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('vat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['vat_id'], ['vat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_rw_provider', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_rw_provider_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw_provider', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_rw_provider_id'))

    op.drop_table('order_rw_provider')
    # ### end Alembic commands ###
