"""initial migration

Revision ID: e46d3907734e
Revises: 6bc5c6f4a352
Create Date: 2024-07-09 17:11:39.518554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46d3907734e'
down_revision: Union[str, None] = '6bc5c6f4a352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw_route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vat_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'vat', ['vat_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw_route', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vat_id')

    # ### end Alembic commands ###
