"""initial migration

Revision ID: eb16a30b32e4
Revises: 80aeed2823ee
Create Date: 2024-07-09 16:57:33.187147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb16a30b32e4'
down_revision: Union[str, None] = '80aeed2823ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw_route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wagon_type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'wagon_types', ['wagon_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_rw_route', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('wagon_type_id')

    # ### end Alembic commands ###
